joesurf433 | 2021-05-11 22:43:26 UTC | #1

Hello. when I run “dfx start” I get these errors and am totally stuck. help.

 thread ‘main’ panicked at ‘Permissions too open for path /examples/c/reverse/.dfx/state/replicated_state/node-100/crypto’, src/crypto_service_provider/secret_key_store/proto_store.rs:95:13 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace thread ‘replica-actor’ panicked at ‘called Result::unwrap() on an Err value: Cannot start the replica: Timeout’, src/dfx/src/actors/replica.rs:310:17 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace(edited)


am just trying to run the C examples

-------------------------

prithvi | 2021-05-11 23:24:09 UTC | #2

Hey @joesurf433 , can you try to do `dfx start --clean` and see if that resolves the issue? This command will clear your local state.

-------------------------

joesurf433 | 2021-05-11 23:31:42 UTC | #3

same error unfortunately

~/bin/dfx start --clean
May 11 23:28:30.179 INFO ic-starter. Configuration: ValidatedConfig { replica_path: Some("/home/xxf/.cache/dfinity/versions/0.6.26/replica"), replica_version: "0.1.0", log_level: Warni
ng, subnet_id: fscpm-uiaaa-aaaaa-aaaap-yai, cargo_bin: "cargo", cargo_opts: "", state_dir: "/media/xxf/Elements/pub/dfinity/examples/c/reverse/.dfx/state/replicated_state", http_listen
_addr: V4(127.0.0.1:0), http_port_file: Some("/media/xxf/Elements/pub/dfinity/examples/c/reverse/.dfx/replica-configuration/replica-1.port"), metrics_addr: None, hypervisor_create_fund
s_whitelist: "*", artifact_pool_dir: "/media/xxf/Elements/pub/dfinity/examples/c/reverse/.dfx/state/replicated_state/node-100/ic_consensus_pool", crypto_root: "/media/xxf/Elements
/pub/dfinity/examples/c/reverse/.dfx/state/replicated_state/node-100/crypto", state_manager_root: "/media/xxf/Elements/pub/dfinity/examples/c/reverse/.dfx/state/replicated_state/node-1
00/state", registry_file: "/media/xxf/Elements/pub/dfinity/examples/c/reverse/.dfx/state/replicated_state/registry.proto", bootstrap_registry: None, state_dir_holder: None }, Applicati
on: starter
May 11 23:28:30.179 INFO Initialize replica configuration "/media/xxf/Elements/pub/dfinity/examples/c/reverse/.dfx/state/replicated_state/ic.json5", Application: starter
thread 'main' panicked at 'Permissions too open for path /media/xxf/Elements/pub/dfinity/examples/c/reverse/.dfx/state/replicated_state/node-100/crypto', src/crypto_service_provider/se
cret_key_store/proto_store.rs:95:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'replica-actor' panicked at 'called `Result::unwrap()` on an `Err` value: Cannot start the replica: Timeout', src/dfx/src/actors/replica.rs:310:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

-------------------------

prithvi | 2021-05-12 00:18:17 UTC | #4

What version of dfx are you using?

-------------------------

joesurf433 | 2021-05-12 00:21:47 UTC | #5

dfx --version, returns this: 
dfx 0.6.26

-------------------------

prithvi | 2021-05-12 00:31:30 UTC | #6

@joesurf433 0.6.26 is our latest official release but won't be for much longer. In the runup to Genesis, our active development has been occurring in the 0.7.0-beta.* releases
You can download the newest release be running the following
```
DFX_VERSION=0.7.0-beta.8 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
```

0.7.0 should be promoted to latest within the next week or so.

Would you mind trying this out with this version?

-------------------------

joesurf433 | 2021-05-12 00:51:02 UTC | #7

I tried it out and still had an error, but it gave me more info. It looks like it didn't like that I was using an external hard drive.

So I moved to my local disk and ran it and it worked. 

Thanks much for your help.

-------------------------

prithvi | 2021-05-12 01:07:17 UTC | #8

> It looks like it didn’t like that I was using an external hard drive.

Ah kk, yeah we've noticed that as well. This is a good data point. Thanks!

-------------------------

