Jesse | 2022-06-14 18:53:13 UTC | #1

Today, i pushed some upgrades to my main.mo canister and some child canisters that are dynamically created in my main.mo canister. When i did this procedure yesterday on my test dapp that i have deployed to the IC, the upgrades went through with no issues. I just pushed the same updates to my main canister and now I’m getting a canister call reject error. I’m not seeing any reason why this upgrade procedure would work just fine yesterday with my test Dapp, but is having issues today with my live version of the Dapp. I’m curious if the issue with merge maturity is causing issues when upgrading canisters.

This is the error I'm getting:
```
index.js:2 Uncaught (in promise) Error: Call was rejected:
  Request ID: 512a969f40a194f0754041f25f0017d66ac990396122076ca621025173cfec99
  Reject code: 4
  Reject text: Canister 7bb7f-zaaaa-aaaaa-aabdq-cai not found

    at oe (index.js:2:94443)
    at async r (index.js:2:98455)
    at async index.js:2:1107263
```

-------------------------

PaulLiu | 2022-06-14 19:08:30 UTC | #2

No, it doesn't seem to be related. This error you got is "Canister not found". Do you have any idea of what is this 7bb7f-zaaaa-aaaaa-aabdq-cai canister? Why your program is trying to call it?

-------------------------

Jesse | 2022-06-14 19:15:07 UTC | #3

I have no clue at the moment. I searched the canister id in canlista and nothing was founded. Could be caused by a failed upgrade when i can `ic.install_code()`. Gonna keep digging

-------------------------

Jesse | 2022-06-14 19:52:46 UTC | #4

That error msg has stopped showing up. I never actually found the cause of it, nor did i make any changes that would have fixed it. I think this issue was being caused by an issue with the ledger. The error would only show when i attempted to retrieve wallet balances Tx history.

-------------------------

