Chacix | 2023-07-19 15:04:33 UTC | #1

vendor.85635a73.js:4 Error: Call was rejected:
  Request ID: 40a35fff4d9c219f911cd5fb80e17fb366169ebd7d2c389d728fb318139e65c1
  Reject code: 5
  Reject text: Canister qohn4-fiaaa-aaaak-ady6a-cai violated contract: RequestInPrep: current_size 11 exceeded the allowed limit local-subnet 10485760 remote-subnet 2097152

-------------------------

Chacix | 2023-07-19 15:05:45 UTC | #2

current_size 11 is slower than local-subnet 10485760 remote-subnet 2097152

-------------------------

Chacix | 2023-07-19 15:06:27 UTC | #3

![image|690x131](upload://8UqrL6jtifhJIhuiueOTUvLibbf.png)

-------------------------

dsarlis | 2023-07-19 15:42:08 UTC | #4

The error message is bad, apologies for that. What it's trying to tell you is that you're hitting the limit of the maximum payload supported when trying to make a call. For calls in the same subnet, that's 10MiB and for calls to remote subnets that's 2MiB. We will improve the error message to make it more useful for future cases.

I suggest you review the places where you're trying to make inter-canister calls and see which one might be trying to add a large payload to the call.

-------------------------

